---
# This task install & configure isc-dhcp-server.

- name: Install isc-dhcp-server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - isc-dhcp-server
  notify: stop_isc-dhcp-server

- name: Set current network interface in /etc/default/isc-dhcp-server
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server

- name: Copying dhcpd.conf configuration file
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
  notify: start_isc-dhcp-server

