---
# This task install & configure isc-dhcp-server.

- name: Install isc-dhcp-server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - isc-dhcp-server

- name: Set current network interface in /etc/default/isc-dhcp-server
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server

- name: Copy dhcpd.conf configuration file
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
  notify: restart_isc-dhcp-server

- name: Start isc-dhcp-server, if not started
  ansible.builtin.service:
    name: isc-dhcp-server.service
    state: started
