---
# This task create repo, install & configure Apache2.

- name: Create repo dir
  file:
    path: /srv/repo/orel/
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Check existing of local repo
  stat:
    path: /srv/repo/orel/repository/conf/distributions
  register: repo_stat_result

- name: Download packages from remote repo
  shell: rsync --delete -aqLz rsync://dl.astralinux.ru/astra/astra/stable/2.12_x86-64/repository /srv/repo/orel
  args:
    warn: no
  when: repo_stat_result.stat.exists == False

- name: Set owner and permissions on /srv/repo
  file:
    path: /srv/repo
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes

- name: Install Apache2
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2

- name: Create symbolic link to repo
  file:
    src: /srv/repo
    dest: /var/www/html/
    path: /srv/repo/orel/
    state: link
    owner: apache
    group: apache
    mode: '0755'

- name: Remove Apache2 default configuration file
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Copy Apache2 configuration file
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart_apache2

- name: Start Apache2, if not started
  ansible.builtin.service:
    name: apache2.service
    state: started
