---
# This task resize logical volume and FS

- name: Resize /dev/vdb physical volume
  shell: pvresize /dev/vdb

#- name: Resize vg_dsk_1 volume group
#  lvg:
#    pvs: /dev/vdb
#    vg: vg_dsk_1

- name: Resize lv_dsk_1 logical volume and FS
  lvol:
    vg: vg_dsk_1
    lv: lv_dsk_1
    size: 100%PVS
    resizefs: true

- name: Mount filesystem
  mount:
    path: /srv
    src: /dev/mapper/vg_dsk_1-lv_dsk_1
    fstype: ext4
    opts: rw,nosuid,noexec
    state: mounted
