---
# This task resize logical volume and FS

- name: Resize vg_dsk_1 volume group
  lvg:
    pvs: /dev/vdb
    vg: vg_dsk_1
    pvresize: yes

- name: Resize lv_dsk_1 logical volume and FS
  lvol:
    vg: vg_dsk_1
    lv: lv_dsk_1
    size: 100%PVS
    resizefs: true
