---
# This task create repo, install & configure Apache2.

- name: Install Apache2
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - apt-mirror

- name: Create repo dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: apt-mirror
    group: apt-mirror
    mode: '0755'
  with_items:
   - /srv/repo/orel/mirror/download.astralinux.ru

- name: Add user apt-mirror to group www-data
  user: name=www-data
        groups=apt-mirror
        append=yes

- name: Edit crontab for user apt-mirror
  shell: sed -i 's/#0 4/0 1/g' /etc/cron.d/apt-mirror

- name: Copy mirror.list configuration file
  template:
    src: mirror.list
    dest: /etc/apt/mirror.list

- name: Copy postmirror.sh script from apt-mirrror default dir
  template:
    src: /var/spool/apt-mirror/var/postmirror.sh
    dest: /srv/repo/orel/postmirror.sh
    remote_src: yes

- name: Copy clean.sh script from apt-mirrror default dir
  template:
    src: /var/spool/apt-mirror/var/clean.sh
    dest: /srv/repo/orel/clean.sh
    remote_src: yes

- name: Create symbolic link to repo
  file:
    src: /srv/repo/orel/mirror/download.astralinux.ru
    dest: /var/www/html/repo
    state: link
    owner: www-data
    group: www-data
    mode: '0755'

- name: Set owner and permissions on /srv/repo
  shell: chmod -R 755 /srv/repo && chown -R apt-mirror:apt-mirror /srv/repo

- name: Remove Apache2 default configuration file
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Copy Apache2 configuration file
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart_apache2

- name: Start Apache2, if not started
  service:
    name: apache2.service
    state: started
