---
# This task create repo, install & configure Apache2.

- name: Install Apache2
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - apt-mirror

- name: Create repo dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items:
   - /srv/repo/orel

- name: Add user apt-mirror to group www-data
  user: name=apt-mirror
        groups=www-data
        append=yes

- name: Edit crontab for user apt-mirror
  shell: sed -i 's/#0 4/0 1/g' /etc/cron.d/apt-mirror

- name: Copy mirror.list configuration file
  template:
    src: mirror.list
    dest: /etc/apt/mirror.list

#  FULL REPO
#- name: Check existing of local FULL repo
#  stat:
#    path: /srv/repo/orel/repository/conf/distributions
#  register: full_repo_stat_result

#- name: Download packages from remote repo (FULL)
#  shell: rsync --delete -aqLz rsync://dl.astralinux.ru/astra/astra/stable/2.12_x86-64/repository /srv/repo/orel
#  args:
#    warn: no
#  when: full_repo_stat_result.stat.exists == False

- name: Set owner and permissions on /srv/repo
  shell: chmod -R 755 /srv/repo && chown -R www-data:www-data /srv/repo

- name: Create symbolic link to repo
  file:
    src: /srv/repo
    dest: /var/www/html/repo
    state: link
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove Apache2 default configuration file
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Copy Apache2 configuration file
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart_apache2

- name: Start Apache2, if not started
  service:
    name: apache2.service
    state: started
