---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install necessary packages
  yum:
    name: "{{ nessecary_packages }}"
    state: present

- name: Set timezone
  timezone:
    name: Europe/Moscow

- name: Firewalld
  block:
    - name: Enable firewalld
      systemd:
        name: firewalld.service
        enabled: yes
        masked: no

    - name: Start firewalld
      systemd:
        name: firewalld.service
        state: started

    - name: Configure firewalld rules
      firewalld:
        service: "{{ firewalld_services }}"
        permanent: yes
        state: enabled
  ignore_errors: yes

- name: Enable up-down-arrow browsing throw commands history
  blockinfile:
    path: /etc/inputrc
    block: |
      #Enable up-down-arrow browse from history
      "\e[A": history-search-backward
      "\e[B": history-search-forward


