---
- name: Enable up-down-arrow browsing throw commands history
  blockinfile:
    path: /etc/inputrc
    block: |
      #Enable up-down-arrow browse from history
      "\e[A": history-search-backward
      "\e[B": history-search-forward

