---
- hosts: my_yc_tst_srv
  tasks:
  - name: Enable up-down-arrow browsing throw commands history - add empty line
  - shell: echo '' >> /etc/inputrc;

  - name: Enable up-down-arrow browsing throw commands history - add comment
  - shell: echo '#Enable up-down-arrow browse from history' >> /etc/inputrc

  - name: Enable up-down-arrow browsing throw commands history - add line #1
  - shell: echo '"\e[A":\ history-search-backward' >> /etc/inputrc

  - name: Enable up-down-arrow browsing throw commands history - add line #2
  - shell: echo '"\e[B":\ history-search-forward' >> /etc/inputrc

