---
# This task install common packages.

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - ufw
   - curl
   - htop
   - tree
   - lvm2
   - dnsutils
